### ISSUE TITLE
Readme and License needed

### ISSUE THREAD

**Issue by pbrkr** [jsbronder/meta-openrc#1]
I'm interested in using openrc in my images and glad to see there is a layer which adds support for this. I'd also be interested in contributing to this layer if it's under an appropriate open source license. Could you add a readme file and a license file to make things a little clearer for me?

If you're unsure of a good license I'd recommend going with the MIT license to match other OpenEmbedded/Yocto Project layers.

**Comment by jsbronder** [comment]
Licensing the same as upstream was always the intent.  Thanks for the kick in the pants to actually add the file saying as much ;)

**Comment by pbrkr** [comment]
Thanks for the quick fix!
