### ISSUE TITLE
Question about non oe-core init script

### ISSUE THREAD

**Issue by mtudan** [jsbronder/meta-openrc#12]
Hi there,

I would like to contribute some additional init scripts for daemons / tools that are not part of the `oe-core` layer. For example, `docker` is part of the `meta-virtualization` layer. Is it okay with you to put that in the `recipes-appends/oe-core` or what do you suggest?

Best,
Matija

**Comment by jsbronder** [comment]
On 10/10/22 12:46 -0700, Matija Tudan wrote:
> Hi there,
> 
> I would like to contribute some additional init scripts for daemons / tools that are not part of the `oe-core` layer. For example, `docker` is part of the `meta-virtualization` layer. Is it okay with you to put that in the `recipes-appends/oe-core` or what do you suggest?

Thanks for your interest, I welcome any contributions!

Let's put appends for meta-virtualization in
`recipes-appends/meta-virtualization` so it's easier to track the appends to the
layers they're applying to.


-- 
Justin Bronder
